MOVEMENT_NO_MOVEMENT = 0
MOVEMENT_MOVING_TOWARDS_CAMERA = 1
MOVEMENT_STARTED_MOVING_AWAY_CAMERA = 2
MOVEMENT_MOVING_AWAY_CAMERA = 3
MOVEMENT_STARTED_MOVING_TOWARDS_CAMERA = 4
MOVEMENT_UNKNOWN_MOVEMENT = -1